name: Poco F6 HyperKernel

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential flex git libssl-dev libelf-dev curl zip

    - name: Clone AnyKernel
      run: |
        git clone https://github.com/osm0sis/AnyKernel3

    - name: Run build script
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh

    - name: Pack flashable zip
      run: |
        cd AnyKernel3
        zip -r PocoF6-HyperKernel.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PocoF6-HyperKernel
        path: AnyKernel3/PocoF6-HyperKernel.zip
