#!/bin/bash

set -e

export ARCH=arm64
export SUBARCH=arm64

echo "Clone Poco F6 kernel source"
git clone --depth=1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource -b peridot-u-oss kernel

echo "Clone clang toolchain"
git clone --depth=1 https://github.com/ZyCromerZ/Clang clang

cd kernel

echo "Inject KernelSU Next"
curl -LSs https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/main/kernel/setup.sh | bash

CONF=arch/arm64/configs/vendor/pineapple_defconfig

echo "Enable virtualization"
cat <<EOF >> $CONF
CONFIG_KVM=y
CONFIG_KVM_ARM_HOST=y
CONFIG_VIRTUALIZATION=y
CONFIG_VHOST_NET=y
CONFIG_VSOCKETS=y
CONFIG_VIRTIO=y
CONFIG_OVERLAY_FS=y
CONFIG_TMPFS_XATTR=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_WIREGUARD=y
EOF

export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH

make O=out vendor/pineapple_defconfig
make -j$(nproc) O=out CC=clang LLVM=1 LLVM_IAS=1

cp out/arch/arm64/boot/Image ../../AnyKernel3/Image
